### ISSUE TITLE
This plugin is showing some error.

### ISSUE THREAD

**Issue by gurjyot** [q2apro/q2apro-recent-events-widget#3]
It was working fine but suddenly this plugin broke and started to show errors.

![recent](https://cloud.githubusercontent.com/assets/6462850/7972233/7a667a82-0a68-11e5-9ff2-83d7f7d55b08.png)

You can also see the question on Q2A QA where I originally asked for the fix.
http://question2answer.org/qa/44903/

**Comment by q2apro** [comment]
Fixed: http://question2answer.org/qa/44903/

**Comment by q2apro** [comment]
Fixed by https://github.com/q2apro/q2apro-recent-events-widget/commit/031b3f77cbb7221741793b5b464ea8d81787a955

**Comment by gurjyot** [comment]
Thanks a lot for the fix Kai. But I you have deprived me of using any of your plugins, so I will not be able to test it...
